import type { Parametres, Vente, Voiture } from "@/types";

const now = new Date().toISOString();

function demoDate(monthsAgo: number): string {
  const d = new Date();
  d.setMonth(d.getMonth() - monthsAgo);
  return d.toISOString().split("T")[0];
}

export const DEMO_VOITURES: Voiture[] = [
  {
    id: "demo-v1",
    created_at: now,
    marque: "Toyota",
    modele: "Camry",
    annee: 2020,
    couleur: "Blanc",
    numero_chassis: "1HGBH41JXMN109186",
    kilometrage: 45000,
    carburant: "Essence",
    transmission: "Automatique",
    photo_url: null,
    statut: "en_stock",
    prix_achat_usd: 12500,
    frais_transport: 2500000,
    prix_vente_fcfa: 9500000,
    prix_vente_usd: null,
    paiement_fournisseur: "paye",
    montant_paye_fournisseur: 12500,
    date_paiement_fournisseur: "2025-11-10",
    date_commande: "2025-09-01",
    date_expedition: "2025-10-01",
    date_arrivee_prevue: "2025-11-01",
    date_arrivee_reelle: "2025-11-05",
    numero_conteneur: "MSCU123456",
    port_depart: "USA",
    notes: "Voiture en excellent état",
  },
  {
    id: "demo-v2",
    created_at: now,
    marque: "Honda",
    modele: "CR-V",
    annee: 2019,
    couleur: "Noir",
    numero_chassis: "2HKRW2H50KH123456",
    kilometrage: 62000,
    carburant: "Essence",
    transmission: "Automatique",
    photo_url: null,
    statut: "en_transit",
    prix_achat_usd: 15000,
    frais_transport: 2800000,
    prix_vente_fcfa: 11000000,
    prix_vente_usd: null,
    paiement_fournisseur: "partiel",
    montant_paye_fournisseur: 8000,
    date_paiement_fournisseur: "2025-12-01",
    date_commande: "2025-10-15",
    date_expedition: "2025-12-10",
    date_arrivee_prevue: "2026-01-20",
    date_arrivee_reelle: null,
    numero_conteneur: "MSCU789012",
    port_depart: "USA",
    notes: null,
  },
  {
    id: "demo-v3",
    created_at: now,
    marque: "BMW",
    modele: "X5",
    annee: 2018,
    couleur: "Gris",
    numero_chassis: "5UXKR0C58J0A12345",
    kilometrage: 78000,
    carburant: "Diesel",
    transmission: "Automatique",
    photo_url: null,
    statut: "commande",
    prix_achat_usd: 25000,
    frais_transport: 3500000,
    prix_vente_fcfa: 18000000,
    prix_vente_usd: null,
    paiement_fournisseur: "non_paye",
    montant_paye_fournisseur: 0,
    date_paiement_fournisseur: null,
    date_commande: "2026-01-05",
    date_expedition: null,
    date_arrivee_prevue: "2026-03-01",
    date_arrivee_reelle: null,
    numero_conteneur: null,
    port_depart: "USA",
    notes: "Commande récente",
  },
  {
    id: "demo-v4",
    created_at: now,
    marque: "Mercedes",
    modele: "C300",
    annee: 2021,
    couleur: "Bleu",
    numero_chassis: "WDDWF4KB0MR123456",
    kilometrage: 32000,
    carburant: "Essence",
    transmission: "Automatique",
    photo_url: null,
    statut: "arrivee",
    prix_achat_usd: 18000,
    frais_transport: 3000000,
    prix_vente_fcfa: 13500000,
    prix_vente_usd: null,
    paiement_fournisseur: "paye",
    montant_paye_fournisseur: 18000,
    date_paiement_fournisseur: "2025-12-20",
    date_commande: "2025-08-01",
    date_expedition: "2025-11-01",
    date_arrivee_prevue: "2025-12-15",
    date_arrivee_reelle: "2025-12-18",
    numero_conteneur: "MSCU345678",
    port_depart: "USA",
    notes: "Au port, en attente de mise en stock",
  },
  {
    id: "demo-v5",
    created_at: now,
    marque: "Toyota",
    modele: "RAV4",
    annee: 2020,
    couleur: "Rouge",
    numero_chassis: "JTMB1RFV0LD123456",
    kilometrage: 51000,
    carburant: "Hybride",
    transmission: "Automatique",
    photo_url: null,
    statut: "vendue",
    prix_achat_usd: 14000,
    frais_transport: 2600000,
    prix_vente_fcfa: 10500000,
    prix_vente_usd: null,
    paiement_fournisseur: "paye",
    montant_paye_fournisseur: 14000,
    date_paiement_fournisseur: "2025-06-01",
    date_commande: "2025-03-01",
    date_expedition: "2025-04-01",
    date_arrivee_prevue: "2025-05-01",
    date_arrivee_reelle: "2025-05-03",
    numero_conteneur: "MSCU567890",
    port_depart: "USA",
    notes: null,
  },
];

export const DEMO_VENTES: Vente[] = [
  {
    id: "demo-sale-1",
    created_at: now,
    voiture_id: "demo-v5",
    client_nom: "Moussa Traoré",
    client_telephone: "+223 70 00 00 00",
    client_adresse: "Bamako, Commune III",
    prix_vente_fcfa: 10500000,
    montant_recu_fcfa: 10500000,
    mode_paiement: "Orange Money",
    statut_paiement: "paye",
    date_vente: demoDate(1),
    numero_facture: `FAC-${new Date().getFullYear()}-001`,
    notes: null,
    status: "active" as const,
    cancelled_at: null,
    cancelled_by: null,
    cancel_reason: null,
    cancelled_from_module: null,
  },
];

export const DEMO_PARAMETRES: Parametres = {
  id: "demo-params",
  created_at: now,
  updated_at: now,
  nom_entreprise: "Auto Mali Import",
  adresse: "Bamako, Mali",
  telephone: "+223 70 12 34 56",
  email: "contact@automali.ml",
  logo_url: null,
  taux_change_usd_fcfa: 600,
};

export function createInitialDemoStore() {
  return {
    _schemaVersion: 2,
    voitures: structuredClone(DEMO_VOITURES),
    ventes: structuredClone(DEMO_VENTES),
    paiements_vente: [] as { id: string; vente_id: string; montant_fcfa: number; mode_paiement: string | null; date_paiement: string; notes: string | null; created_at: string }[],
    parametres: structuredClone(DEMO_PARAMETRES),
  };
}
